name: WSPR
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - pandas
  - torchvision
  - pytorch-cuda=12.1
  - torchaudio
  - ipykernel
  - pillow[version='>=10.0']
